services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: relmag_db
      POSTGRES_USER: relmag_admin
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: